// import 'package:flutter/material.dart';

// class Image{

//   List<AssetImage> get_icons(){
//     return _icons;
//   }

//   List<AssetImage> _icons = [
//     AssetImage(
//       'assets/icon/icon-1.jpeg',
//     ),
//     AssetImage(
//       'assets/icon/icon-2.jpeg',
//     ),
//     AssetImage(
//       'assets/icon/icon-3.jpeg',
//     ),
//     AssetImage(
//       'assets/icon/icon-4.jpeg',
//     ),
//     AssetImage(
//       'assets/icon/icon-5.jpeg',
//     ),
//     AssetImage(
//       'assets/icon/icon-6.jpeg',
//     ),
//     AssetImage(
//       'assets/icon/icon-7.jpeg',
//     ),
//     AssetImage(
//       'assets/icon/icon-8.jpeg',
//     ),
//     AssetImage(
//       'assets/icon/icon-9.jpeg',
//     ),
//     AssetImage(
//       'assets/icon/icon-10.jpeg',
//     ),
//   ];

//      final List<AssetImage> _imagesOfBg = [
//     AssetImage(
//       'assets/images/IMAGE-1.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-2.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-3.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-4.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-5.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-6.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-7.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-8.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-9.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-10.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-11.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-12.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-13.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-14.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-15.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-16.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-17.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-18.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-19.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-20.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-21.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-22.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-23.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-24.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-25.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-26.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-27.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-28.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-29.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-30.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-31.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-32.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-33.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-34.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-35.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-36.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-37.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-38.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-39.jpeg',
//     ),
//     AssetImage(
//       'assets/images/IMAGE-40.jpeg',
//     ),
//   ];
// }