name: kakeibogram
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  charts_flutter: ^0.6.0
  image_picker: ^0.6.0+17
  path_provider: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: GreatVibes-Regular
      fonts:
      - asset: assets/fonts/GreatVibes-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/IMAGE-1.jpeg
    - assets/images/IMAGE-2.jpeg
    - assets/images/IMAGE-3.jpeg
    - assets/images/IMAGE-4.jpeg
    - assets/images/IMAGE-5.jpeg
    - assets/images/IMAGE-6.jpeg
    - assets/images/IMAGE-7.jpeg
    - assets/images/IMAGE-8.jpeg
    - assets/images/IMAGE-9.jpeg
    - assets/images/IMAGE-10.jpeg
    - assets/images/IMAGE-11.jpeg
    - assets/images/IMAGE-12.jpeg
    - assets/images/IMAGE-13.jpeg
    - assets/images/IMAGE-14.jpeg
    - assets/images/IMAGE-15.jpeg
    - assets/images/IMAGE-16.jpeg
    - assets/images/IMAGE-17.jpeg
    - assets/images/IMAGE-18.jpeg
    - assets/images/IMAGE-19.jpeg
    - assets/images/IMAGE-20.jpeg
    - assets/images/IMAGE-21.jpeg
    - assets/images/IMAGE-22.jpeg
    - assets/images/IMAGE-23.jpeg
    - assets/images/IMAGE-24.jpeg
    - assets/images/IMAGE-25.jpeg
    - assets/images/IMAGE-26.jpeg
    - assets/images/IMAGE-27.jpeg
    - assets/images/IMAGE-28.jpeg
    - assets/images/IMAGE-29.jpeg
    - assets/images/IMAGE-30.jpeg
    - assets/images/IMAGE-31.jpeg
    - assets/images/IMAGE-32.jpeg
    - assets/images/IMAGE-33.jpeg
    - assets/images/IMAGE-34.jpeg
    - assets/images/IMAGE-35.jpeg
    - assets/images/IMAGE-36.jpeg
    - assets/images/IMAGE-37.jpeg
    - assets/images/IMAGE-38.jpeg
    - assets/images/IMAGE-39.jpeg
    - assets/images/IMAGE-40.jpeg
    # - assets/images/IMAGE-41.jpeg
    # - assets/images/IMAGE-42.jpeg
    # - assets/images/IMAGE-43.jpeg
    # - assets/images/IMAGE-44.jpeg
    # - assets/images/IMAGE-45.jpeg
    # - assets/images/IMAGE-46.jpeg
    # - assets/images/IMAGE-47.jpeg
    # - assets/images/IMAGE-48.jpeg
    # - assets/images/IMAGE-49.jpeg
    # - assets/images/IMAGE-50.jpeg
    # - assets/images/IMAGE-51.jpeg
    # - assets/images/IMAGE-52.jpeg
    # - assets/images/IMAGE-53.jpeg
    # - assets/images/IMAGE-54.jpeg
    # - assets/images/IMAGE-55.jpeg
    # - assets/images/IMAGE-56.jpeg
    # - assets/images/IMAGE-57.jpeg
    # - assets/images/IMAGE-58.jpeg
    - assets/icon/icon-1.jpeg
    - assets/icon/icon-2.jpeg
    - assets/icon/icon-3.jpeg
    - assets/icon/icon-4.jpeg
    - assets/icon/icon-5.jpeg
    - assets/icon/icon-6.jpeg
    - assets/icon/icon-7.jpeg
    - assets/icon/icon-8.jpeg
    - assets/icon/icon-9.jpeg
    - assets/icon/icon-10.jpeg
    - assets/graph/graph1.png
    - assets/graph/graph2.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
